spring:
  data:
    mongodb:
      uri: mongodb://suzhy:1111@127.0.0.1:27017/testdb
#      host: 127.0.0.1
#      port: 27017
#      database: testdb
#      username: suzhy
#      password: 1111
#      authentication-database: testdb


logging:
  pattern:
    console: "%m%n"
